# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c689765a6c782bbe482672a64befd55e71f538da17a0d91d8e7bbb10027f8959acf627ca31adf1af4ce06a7d2a72422fc5a2bee75ae358b5b58e5f6968b42c6e

test:
  secret_key_base: c407ae369f0fc13182cdede5619e115321d39bc56d6c47fc197bc1feb9529f77b310096a6cbd3ad36700cf282a0dfecd325780306ff6fff5f99ffffba3abec83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
